# Generated by Django 4.0 on 2022-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_dp',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Background Pic'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Profile Pic'),
        ),
    ]
