# Generated by Django 4.0 on 2022-01-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_background_dp_alter_userprofile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_dp',
            field=models.FileField(blank=True, null=True, upload_to='back_dp', verbose_name='Background Pic'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.FileField(blank=True, null=True, upload_to='dp', verbose_name='Profile Pic'),
        ),
    ]
