# Generated by Django 4.0 on 2022-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_background_dp_alter_userprofile_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Tech1',
            field=models.ImageField(max_length=150, null=True, upload_to='tech', verbose_name='Technology 1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Tech2',
            field=models.ImageField(max_length=150, null=True, upload_to='tech', verbose_name='Technology 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(max_length=50, null=True, verbose_name='Role that best justifies you'),
        ),
    ]
